from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = PROJECT_ROOT / "outputs" / "results"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize per-building metrics by building type for one experiment file."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=RESULTS_DIR / "building_aware_itransformer_250_noweather_per_building_metrics.csv",
        help="Path to a per-building metrics CSV generated by one active paper experiment.",
    )
    parser.add_argument(
        "--group-column",
        type=str,
        default="primaryspaceusage",
        help="Metadata column used to group buildings.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = args.input.resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Missing per-building metrics file: {input_path}")

    metrics = pd.read_csv(input_path)
    if args.group_column not in metrics.columns:
        raise ValueError(f"Column '{args.group_column}' was not found in {input_path.name}.")

    summary = (
        metrics.groupby(["split", args.group_column, "model"], dropna=False)
        .agg(
            num_buildings=("building_id", "nunique"),
            MAE=("MAE", "mean"),
            RMSE=("RMSE", "mean"),
            NMAE=("NMAE", "mean"),
            CVRMSE=("CVRMSE", "mean"),
        )
        .reset_index()
        .sort_values(["split", args.group_column, "RMSE", "model"])
    )

    output_path = input_path.with_name(f"{input_path.stem}_by_{args.group_column}.csv")
    summary.to_csv(output_path, index=False)
    print(summary.to_string(index=False))
    print(f"\nSaved building-type summary: {output_path}")


if __name__ == "__main__":
    main()
